# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for f5122 configurations
Name: jolla-configuration-f5122
Requires:
- patterns-sailfish-device-configuration-f5122

Summary: Jolla Configuration f5122

