%package -n patterns-sailfish-device-configuration-f5122
Summary: Jolla Configuration f5122
Requires: patterns-sailfish-device-configuration-common-f5122
Requires: patterns-sailfish-device-adaptation-f512x

Requires: patterns-sailfish-cellular-apps

Requires: droid-config-f5122-sailfish
Requires: droid-config-f5122-pulseaudio-settings
Requires: droid-config-f5122-policy-settings
Requires: droid-config-f5122-preinit-plugin
Requires: droid-config-f5122-flashing
Requires: droid-config-f5122-bluez5
Requires: droid-hal-version-f5122

Requires: droid-system-f5122

Requires: jolla-settings-networking-multisim
Requires: sailfish-content-graphics-z%{icon_res}
Requires: geoclue-provider-mlsdb
Requires: jolla-settings-system-flashlight
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-f5122
Pattern with packages for f5122 configurations

%files -n patterns-sailfish-device-configuration-f5122
