%package -n patterns-sailfish-device-configuration-f5121
Summary: Jolla Configuration f5121
Requires: patterns-sailfish-device-configuration-common-f5121
Requires: patterns-sailfish-device-adaptation-f512x

Requires: patterns-sailfish-cellular-apps

Requires: droid-config-f5121-sailfish
Requires: droid-config-f5121-pulseaudio-settings
Requires: droid-config-f5121-policy-settings
Requires: droid-config-f5121-preinit-plugin
Requires: droid-config-f5121-flashing
Requires: droid-config-f5121-bluez5
Requires: droid-hal-version-f5121

Requires: droid-system-f5121

Requires: sailfish-content-graphics-z%{icon_res}
Requires: geoclue-provider-mlsdb
Requires: jolla-settings-system-flashlight
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-f5121
Pattern with packages for f5121 configurations

%files -n patterns-sailfish-device-configuration-f5121
